// <auto-generated />
namespace Data.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class initialmssqlprod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmssqlprod));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302016129_initial mssql prod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
