// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Data.Npgsql.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class institutiononemployeetitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(institutiononemployeetitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301703458_institution on employee title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
