// <auto-generated />
namespace Data.Npgsql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emailsettingsforanorganization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailsettingsforanorganization));
        
        string IMigrationMetadata.Id
        {
            get { return "201707260845164_email settings for an organization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
