// <auto-generated />
namespace Data.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedrolestocontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrolestocontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201707211149105_added roles to context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
