// <auto-generated />
namespace Data.Npgsql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedfriendshiptableasrelationbetweenemployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfriendshiptableasrelationbetweenemployees));
        
        string IMigrationMetadata.Id
        {
            get { return "201707221737058_added friendship table as relation between employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
